#!/bin/sh

[ ! -d  /sys/class/power_supply/BAT0 ] && printf "❓" && return 1
capacity=$(cat /sys/class/power_supply/BAT0/capacity)
status=$(cat /sys/class/power_supply/BAT0/status)
[ $status = "Discharging" ] && [ $capacity -le 25 ] && warn="❗" 
printf "$warn$(printf $status | sed "s/Charging/🔌/g;s/Discharging/🔋/g;s/Full/⚡/g;s/Unknown/❓/g")$capacity%s" "%"

