#!/bin/sh

[ "$(pactl list sinks | grep Mute)" = "	Mute: yes" ] && printf "🔇" && exit 0

vol=$(pactl list sinks | grep "Volume: front-left" )
vol=${vol%%%*}
vol=${vol##* }

[ $(( $vol <= 0 )) = 1 ] && printf "🔈" && exit 0
( [ $(( $vol <= 50 )) = 1 ] && printf "🔉" ) || \
( [ $(( $vol > 100 )) = 1 ] && printf "❗" ) || printf "🔊" 

printf "%3s" "$vol%"
